### ISSUE TITLE
Use BigDecimal instead of usize for count

### ISSUE THREAD

**Issue by sehkone** [petabi/structured#72]
Every field dealing with a number of counting something like events should be represented as `BigDecimal`.

**Comment by msk** [comment]
I don't think this is a good idea. Structured makes use of many low-level techniques for memory efficiency and processing speed. Using `BigDecimal` instead of a primitive type with a known size, e.g., `f64`, would force structured to replace many of those techniques, and thus require more memory and more CPU time.

If an application needs to use, `BigDecimal`, I recommend that it keep Structured's data structure (`Table` or `Array`) as much as possible, and convert values to `BigDecimal`only when `BigDecimal` must be used.

**Comment by sehkone** [comment]
Got it.
